#!/usr/bin/env python3
"""Writes js/dims.js: intrinsic width/height of every image/video under Assets/,
keyed by the percent-encoded src used in data.js, so tiles can reserve their
aspect ratio before the file loads (no layout jumps while scrolling)."""
import json, os, subprocess, sys
from urllib.parse import quote

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)
exts = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".mp4", ".webm", ".mov"}
out = {}
for d, _, files in os.walk("Assets"):
    for f in files:
        if os.path.splitext(f)[1].lower() not in exts:
            continue
        p = os.path.join(d, f)
        try:
            r = subprocess.run(
                ["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries",
                 "stream=width,height:stream_side_data=rotation", "-of", "json", p],
                capture_output=True, text=True, check=True)
            s = json.loads(r.stdout)["streams"][0]
            w, h = s["width"], s["height"]
            if w <= 0 or h <= 0:
                raise ValueError("no size")
            rot = abs(int((s.get("side_data_list") or [{}])[0].get("rotation", 0)))
            if rot in (90, 270):
                w, h = h, w
            out["/".join(quote(x, safe="") for x in p.split(os.sep))] = [w, h]
        except Exception as e:
            # ffprobe can't read animated webp — ImageMagick can
            try:
                r = subprocess.run(["identify", "-format", "%w %h", p + "[0]"], capture_output=True, text=True, check=True)
                w, h = map(int, r.stdout.split())
                out["/".join(quote(x, safe="") for x in p.split(os.sep))] = [w, h]
            except Exception:
                print("skip", p, e, file=sys.stderr)
with open("js/dims.js", "w") as fh:
    fh.write("// generated by scripts/gen_dims.py — do not edit\nconst MEDIA_DIMS = ")
    json.dump(out, fh, separators=(",", ":"))
    fh.write(";\n")
print(len(out), "entries")
